import os
import re
import glob
import copy
from lxml import etree

# Configuration
SOURCE_DIR = "xml_depart"
OUTPUT_DIR = "transformation_automatique"
ANALYSE_DIR = os.path.join(SOURCE_DIR, "analyse")
ROMAN_DIR = os.path.join(SOURCE_DIR, "roman")

# XSLT files
XSLT_TRANSFORMATION = "transformation.xsl"
XSLT_APPARAT = "apparat.xsl"
XSLT_REPERTOIRE = "repertoire.xsl"

# TEI Namespace
TEI_NS = "http://www.tei-c.org/ns/1.0"
HTML_NS = "http://www.w3.org/1999/xhtml"
NS_MAP = {None: TEI_NS, 'html': HTML_NS}

def ensure_dir(directory):
    if not os.path.exists(directory):
        os.makedirs(directory)

def clean_text(text):
    if text is None:
        return ""
    return re.sub(r'[\n\t\s]+', ' ', text).strip()

def create_tei_base(title):
    root = etree.Element(f"{{{TEI_NS}}}TEI", nsmap=NS_MAP)
    header = etree.SubElement(root, f"{{{TEI_NS}}}teiHeader")
    fileDesc = etree.SubElement(header, f"{{{TEI_NS}}}fileDesc")
    titleStmt = etree.SubElement(fileDesc, f"{{{TEI_NS}}}titleStmt")
    t = etree.SubElement(titleStmt, f"{{{TEI_NS}}}title")
    t.text = title
    etree.SubElement(fileDesc, f"{{{TEI_NS}}}publicationStmt")
    sourceDesc = etree.SubElement(fileDesc, f"{{{TEI_NS}}}sourceDesc")
    p = etree.SubElement(sourceDesc, f"{{{TEI_NS}}}p")
    p.text = "Generated by automated transformation script"
    text_elem = etree.SubElement(root, f"{{{TEI_NS}}}text")
    body = etree.SubElement(text_elem, f"{{{TEI_NS}}}body")
    div = etree.SubElement(body, f"{{{TEI_NS}}}div")
    return root, div

def transform_glossary():
    print("Transforming Glossary...")
    files = glob.glob(os.path.join(ANALYSE_DIR, "glossaire", "glossaire_*.xml"))
    root, div = create_tei_base("Glossaire")
    
    files.sort()
    used_ids = set()
    
    for f in files:
        parser = etree.XMLParser(remove_blank_text=True)
        tree = etree.parse(f, parser)
        
        tables = tree.xpath("//tei:table[not(@xml:id='draggable')]", namespaces={'tei': TEI_NS})
        for table in tables:
            rows = table.xpath("./tei:row", namespaces={'tei': TEI_NS})
            for row in rows:
                cells = row.xpath("./tei:cell", namespaces={'tei': TEI_NS})
                if len(cells) >= 2:
                    term_cell = cells[0]
                    def_cell = cells[1]
                    
                    term_id = term_cell.get("{http://www.w3.org/XML/1998/namespace}id")
                    term_text = "".join(term_cell.itertext()).strip()
                    
                    if not term_text or term_text == "Terme": continue

                    entry = etree.SubElement(div, f"{{{TEI_NS}}}entry")
                    
                    base_id = term_id if term_id else term_text.lower().replace(" ", "_").replace("'", "_")
                    base_id = re.sub(r'[^a-zA-Z0-9_.-]', '_', base_id)
                    unique_id = base_id
                    counter = 1
                    while unique_id in used_ids:
                        unique_id = f"{base_id}_{counter}"
                        counter += 1
                    used_ids.add(unique_id)
                    entry.set("{http://www.w3.org/XML/1998/namespace}id", unique_id)

                    form = etree.SubElement(entry, f"{{{TEI_NS}}}form")
                    form.text = term_text
                    
                    definition = etree.SubElement(entry, f"{{{TEI_NS}}}def")
                    for child in def_cell:
                        definition.append(copy.deepcopy(child))
                    if not list(definition) and def_cell.text:
                        definition.text = def_cell.text

    output_path = os.path.join(OUTPUT_DIR, "glossaire.xml")
    with open(output_path, "wb") as f_out:
        f_out.write(etree.tostring(root, pretty_print=True, xml_declaration=True, encoding="UTF-8"))

def transform_note_grp(subdir, title, output_filename, is_already_notes=False):
    print(f"Transforming {title}...")
    pattern = "note_*.xml" if subdir == "notes" else f"{subdir[:-1] if subdir != 'repertoire' else 'repertoire'}_*.xml"
    if subdir == "repertoire": pattern = "repertoire_*.xml"
    if subdir == "personnages": pattern = "personnage_*.xml"
    
    files = glob.glob(os.path.join(ANALYSE_DIR, subdir, pattern))
    root, div = create_tei_base(title)
    noteGrp = etree.SubElement(div, f"{{{TEI_NS}}}noteGrp")
    
    files.sort()
    used_ids = set()
    
    for f in files:
        parser = etree.XMLParser(remove_blank_text=True)
        tree = etree.parse(f, parser)
        
        if is_already_notes:
            notes = tree.xpath("//tei:note", namespaces={'tei': TEI_NS})
            ana_match = re.search(r'note_(\d+)', os.path.basename(f))
            ana = ana_match.group(1) if ana_match else ""
            for note_src in notes:
                note = copy.deepcopy(note_src)
                if ana:
                    note.set("ana", ana)
                
                orig_id = note.get("{http://www.w3.org/XML/1998/namespace}id")
                if orig_id:
                    unique_id = orig_id
                    counter = 1
                    while unique_id in used_ids:
                        unique_id = f"{orig_id}_{counter}"
                        counter += 1
                    used_ids.add(unique_id)
                    note.set("{http://www.w3.org/XML/1998/namespace}id", unique_id)
                
                noteGrp.append(note)
        else:
            tables = tree.xpath("//tei:table[not(@xml:id='draggable')]", namespaces={'tei': TEI_NS})
            for table in tables:
                rows = table.xpath("./tei:row", namespaces={'tei': TEI_NS})
                for row in rows:
                    cells = row.xpath("./tei:cell", namespaces={'tei': TEI_NS})
                    if len(cells) >= 1:
                        note = etree.SubElement(noteGrp, f"{{{TEI_NS}}}note")
                        
                        label_text = "".join(cells[0].itertext()).strip()
                        if not label_text or label_text in ["Nom", "Personnage"]: continue
                        
                        label_text = re.sub(r'[:η\s]+$', '', label_text)
                        label = etree.SubElement(note, f"{{{TEI_NS}}}label")
                        label.text = label_text
                        
                        orig_id = cells[0].get("{http://www.w3.org/XML/1998/namespace}id")
                        base_id = orig_id if orig_id else label_text.lower().replace(" ", "_").replace("'", "_")
                        base_id = re.sub(r'[^a-zA-Z0-9_.-]', '_', base_id)
                        
                        unique_id = base_id
                        counter = 1
                        while unique_id in used_ids:
                            unique_id = f"{base_id}_{counter}"
                            counter += 1
                        used_ids.add(unique_id)
                        note.set("{http://www.w3.org/XML/1998/namespace}id", unique_id)

                        for i in range(1, len(cells)):
                            for child in cells[i]:
                                note.append(copy.deepcopy(child))
                            if not list(cells[i]) and cells[i].text:
                                p = etree.SubElement(note, f"{{{TEI_NS}}}p")
                                p.text = cells[i].text

    output_path = os.path.join(OUTPUT_DIR, output_filename)
    with open(output_path, "wb") as f_out:
        f_out.write(etree.tostring(root, pretty_print=True, xml_declaration=True, encoding="UTF-8"))

def main():
    ensure_dir(OUTPUT_DIR)
    
    # 1. Apparatus
    transform_glossary()
    transform_note_grp("notes", "Notes", "notes_2.xml")
    transform_note_grp("personnages", "Personnages", "personnages.xml")
    transform_note_grp("repertoire", "Répertoire", "repertoire.xml")
    
def generate_index_html():
    print("Generating index.html...")
    html_content = """
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>L'Astrée - Index Général</title>
    <link rel="stylesheet" href="style.css">
    <style>
        body { font-family: 'Inter', sans-serif; background: #f4f1ea; color: #2c2c2c; padding: 40px; }
        .container { max-width: 1000px; margin: 0 auto; background: white; padding: 40px; border-radius: 12px; box-shadow: 0 10px 30px rgba(0,0,0,0.1); }
        h1 { color: #8b4513; text-align: center; font-size: 2.5em; margin-bottom: 40px; }
        .section { margin-bottom: 40px; }
        h2 { border-bottom: 2px solid #8b4513; padding-bottom: 10px; color: #8b4513; margin-top: 30px; }
        .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 15px; margin-top: 20px; }
        .card { background: #fafafa; padding: 15px; border-radius: 8px; border: 1px solid #eee; text-decoration: none; color: #333; transition: all 0.3s ease; text-align: center; font-weight: 500; }
        .card:hover { transform: translateY(-5px); box-shadow: 0 5px 15px rgba(0,0,0,0.1); border-color: #8b4513; color: #8b4513; }
        .card.apparatus { background: #fff9f0; border-color: #ffd8a8; }
        .card.apparatus:hover { background: #fff3e0; }
    </style>
</head>
<body>
    <div class="container">
        <h1>L'Astrée d'Honoré d'Urfé</h1>
        
        <div class="section">
            <h2>Apparat Critique</h2>
            <div class="grid">
                <a href="glossaire.html" class="card apparatus">Glossaire</a>
                <a href="notes_2.html" class="card apparatus">Notes</a>
                <a href="personnages.html" class="card apparatus">Personnages</a>
                <a href="repertoire.html" class="card apparatus">Répertoire</a>
            </div>
        </div>

        <div class="section">
            <h2>Édition de Référence (1621)</h2>
            <div class="grid">
    """
    
    # List books
    for part in range(1, 5):
        for book in range(1, 13):
            filename = f"livre{part}_{book}.html"
            if os.path.exists(os.path.join(OUTPUT_DIR, filename)):
                html_content += f'<a href="{filename}" class="card">Partie {part}, Livre {book}</a>\n'

    html_content += """
            </div>
        </div>

        <div class="section">
            <h2>Édition Fonctionnelle</h2>
            <div class="grid">
    """
    
    for part in range(1, 5):
        for book in range(1, 13):
            filename = f"livre{part}_{book}_f.html"
            if os.path.exists(os.path.join(OUTPUT_DIR, filename)):
                html_content += f'<a href="{filename}" class="card">Partie {part}, Livre {book} (F)</a>\n'

    html_content += """
            </div>
        </div>
    </div>
</body>
</html>
    """
    with open(os.path.join(OUTPUT_DIR, "index.html"), "w", encoding="UTF-8") as f:
        f.write(html_content)

def fix_links(root):
    # Fix persName ref
    for elem in root.xpath("//tei:persName[@ref]", namespaces={'tei': TEI_NS}):
        ref = elem.get("ref")
        # personnage_aa.html#2_astree -> personnages.html#2_astree
        # OR personnage_aa.html#astree -> personnages.html#astree
        m = re.search(r'personnage_[a-z]+\.html#(?:(\d+)_)?([a-z_0-9]+)', ref)
        if m:
            prefix = f"{m.group(1)}_" if m.group(1) else ""
            elem.set("ref", f"personnages.html#{prefix}{m.group(2)}")
        else:
            m = re.search(r'personnages\.html#([a-z_0-9]+)_(\d+)', ref)
            if m:
                elem.set("ref", f"personnages.html#{m.group(2)}_{m.group(1)}")

    # Fix term ref (glossary)
    for elem in root.xpath("//tei:term[@ref]", namespaces={'tei': TEI_NS}):
        ref = elem.get("ref")
        m = re.search(r'glossaire_[a-z]+\.html#([a-z_0-9]+)', ref)
        if m:
            elem.set("ref", f"glossaire.html#{m.group(1)}")

    # Fix rs ref (repertoire)
    for elem in root.xpath("//tei:rs[@ref]", namespaces={'tei': TEI_NS}):
        ref = elem.get("ref")
        m = re.search(r'repertoire_[a-z]+\.html#(?:(\d+)_)?([a-z_0-9]+)', ref)
        if m:
            prefix = f"{m.group(1)}_" if m.group(1) else ""
            elem.set("ref", f"repertoire.html#{prefix}{m.group(2)}")

    # Fix note target
    for elem in root.xpath("//tei:note[@target]", namespaces={'tei': TEI_NS}):
        target = elem.get("target")
        m = re.search(r'note_(\d+)\.html#(?:\d+_)?([a-z_0-9]+)', target)
        if m:
            elem.set("target", f"notes_{m.group(1)}.html#{m.group(2)}")

def clean_tei_roman(tree, is_functional=False):
    # Remove navigation (any p that looks like a nav or has multiple refs)
    for p in tree.xpath("//tei:p[tei:ref and count(tei:ref) > 1]", namespaces={'tei': TEI_NS}):
        p.getparent().remove(p)
    
    if is_functional:
        body = tree.xpath("//tei:body", namespaces={'tei': TEI_NS})[0]
        
        # Remove everything before the first div that starts with a head (usually the book/part title)
        # OR the first p that contains a pb/graphic lettrine.
        # But looking at livre2_1_f.xml model, it has <head> elements for title first.
        
        children = list(body)
        keep_from_index = -1
        
        # Look for the real content start
        for i, child in enumerate(children):
            # The real content usually starts with a <div> containing a <head> 
            # OR a <head> directly in body (like livre2_1_f.xml model)
            if child.tag == f"{{{TEI_NS}}}head" or child.tag == f"{{{TEI_NS}}}div":
                # Check if it's not a nav div (one that contains many refs)
                if not child.xpath(".//tei:ref[contains(@target, '_analyse/')]", namespaces={'tei': TEI_NS}):
                    keep_from_index = i
                    break
            # Or it might start with a <p> containing a <pb> or a lettrine <graphic>
            if child.tag == f"{{{TEI_NS}}}p" and (child.xpath(".//tei:pb", namespaces={'tei': TEI_NS}) or child.xpath(".//tei:graphic[contains(@url, 'page1')]", namespaces={'tei': TEI_NS})):
                keep_from_index = i
                break

        if keep_from_index != -1:
            # Remove everything before the identified start index
            for child in children[:keep_from_index]:
                body.remove(child)
        
        # Also remove everything after the main content
        # Usually trails off into Référence électronique or Google Analytics
        # In the model livre2_1_f.xml, it ends after the body.
        # Let's find common footer elements and remove them and everything after.
        children_after = list(body)
        remove_from_index = -1
        for i, child in enumerate(children_after):
            if (child.tag == f"{{{TEI_NS}}}p" and child.get("rend") == "center_t titre9" and "Référence électronique" in "".join(child.itertext())) or \
               (child.tag == f"{{{TEI_NS}}}ref" and "statcounter.com" in (child.get("target") or "")):
                remove_from_index = i
                break
        
        if remove_from_index != -1:
            for child in children_after[remove_from_index:]:
                body.remove(child)
        
        # Final cleanup: remove residual empty paragraphs or line breaks at the very beginning of body
        for child in list(body):
            if child.tag == f"{{{TEI_NS}}}lb" or (child.tag == f"{{{TEI_NS}}}p" and not child.text and not list(child)):
                body.remove(child)
            else:
                break

    # Remove signet graphics and their hi containers
    for graphic in tree.xpath("//tei:graphic[contains(@url, 'signet')]", namespaces={'tei': TEI_NS}):
        parent = graphic.getparent()
        if parent is not None:
            if parent.tag in [f"{{{TEI_NS}}}hi", f"{{{TEI_NS}}}p"]:
                gp = parent.getparent()
                if gp is not None: gp.remove(parent)
            else:
                parent.remove(graphic)
                
    # Update image paths (remove ../../../images/ -> images/)
    for graphic in tree.xpath("//tei:graphic[@url]", namespaces={'tei': TEI_NS}):
        url = graphic.get("url")
        if "../../../images/" in url:
            graphic.set("url", url.replace("../../../images/", "images/"))

    fix_links(tree)

def apply_xslt(xml_path, xsl_path, output_html_path):
    print(f"Applying {xsl_path} to {xml_path}...")
    xml_tree = etree.parse(xml_path)
    xslt_tree = etree.parse(xsl_path)
    transform = etree.XSLT(xslt_tree)
    result_tree = transform(xml_tree)
    with open(output_html_path, "wb") as f_out:
        f_out.write(etree.tostring(result_tree, pretty_print=True, method="html", encoding="UTF-8"))

def transform_roman():
    print("Transforming Roman files...")
    # Process reference files
    ref_files = glob.glob(os.path.join(ROMAN_DIR, "reference", "*.xml"))
    for f in ref_files:
        parser = etree.XMLParser(remove_blank_text=True)
        tree = etree.parse(f, parser)
        clean_tei_roman(tree, is_functional=False)
        
        # Output filename: 21_2_livre_1.tei.xml -> livre2_1.xml
        basename = os.path.basename(f)
        m = re.search(r'21_(\d)_livre_(\d+)', basename)
        if m:
            out_xml = f"livre{m.group(1)}_{m.group(2)}.xml"
            output_path = os.path.join(OUTPUT_DIR, out_xml)
            with open(output_path, "wb") as f_out:
                f_out.write(etree.tostring(tree, pretty_print=True, xml_declaration=True, encoding="UTF-8"))
            # Apply XSLT
            apply_xslt(output_path, XSLT_TRANSFORMATION, output_path.replace(".xml", ".html"))

    # Process fonctionnelle files
    func_files = glob.glob(os.path.join(ROMAN_DIR, "fonctionnelle", "*.xml"))
    for f in func_files:
        parser = etree.XMLParser(remove_blank_text=True)
        tree = etree.parse(f, parser)
        clean_tei_roman(tree, is_functional=True)
        
        # Output filename: fonctionnelle_2_livre_1.xml -> livre2_1_f.xml
        basename = os.path.basename(f)
        m = re.search(r'fonctionnelle_(\d)_livre_(\d+)', basename)
        if m:
            out_xml = f"livre{m.group(1)}_{m.group(2)}_f.xml"
            output_path = os.path.join(OUTPUT_DIR, out_xml)
            with open(output_path, "wb") as f_out:
                f_out.write(etree.tostring(tree, pretty_print=True, xml_declaration=True, encoding="UTF-8"))
            # Apply XSLT
            apply_xslt(output_path, XSLT_TRANSFORMATION, output_path.replace(".xml", ".html"))

def main():
    ensure_dir(OUTPUT_DIR)
    
    # 1. Apparatus
    transform_glossary()
    transform_note_grp("notes", "Notes", "notes_2.xml", is_already_notes=True)
    transform_note_grp("personnages", "Personnages", "personnages.xml")
    transform_note_grp("repertoire", "Répertoire", "repertoire.xml")
    
    # 2. Roman
    transform_roman()
    
    # 3. Final Apparatus HTML (using their specific XSLTs)
    apply_xslt(os.path.join(OUTPUT_DIR, "glossaire.xml"), XSLT_APPARAT, os.path.join(OUTPUT_DIR, "glossaire.html"))
    apply_xslt(os.path.join(OUTPUT_DIR, "notes_2.xml"), XSLT_APPARAT, os.path.join(OUTPUT_DIR, "notes_2.html"))
    apply_xslt(os.path.join(OUTPUT_DIR, "personnages.xml"), XSLT_REPERTOIRE, os.path.join(OUTPUT_DIR, "personnages.html"))
    apply_xslt(os.path.join(OUTPUT_DIR, "repertoire.xml"), XSLT_REPERTOIRE, os.path.join(OUTPUT_DIR, "repertoire.html"))

    # 4. Generate Index
    generate_index_html()

    print("Done!")

if __name__ == "__main__":
    main()
