<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns="http://www.tei-c.org/ns/1.0"
  xmlns:tei="http://www.tei-c.org/ns/1.0"
  xmlns:foo="foo/bar"
  xmlns:html="http://www.w3.org/1999/xhtml"
  exclude-result-prefixes="tei xs foo html"
  xpath-default-namespace="http://www.w3.org/1999/xhtml"
  version="3.0">
  
  <xsl:output method="xml" indent="yes" encoding="UTF-8"/>
  <xsl:strip-space elements="*"/>
  
  <xsl:variable name="documentName"
    select="substring-before(tokenize(base-uri(), '/')[last()], '.')"/>
  
  <!-- ROOT DOCUMENT -->
  <xsl:template match="/">
    <TEI xmlns="http://www.tei-c.org/ns/1.0"
      xmlns:html="http://www.w3.org/1999/xhtml">
      
      <teiHeader>
        <fileDesc>
          <titleStmt>
            <title>Glossaire</title>
          </titleStmt>
          
          <publicationStmt>
            <authority/>
          </publicationStmt>
          
          <sourceDesc>
            <p>Generated by automated transformation script</p>
          </sourceDesc>
        </fileDesc>
      </teiHeader>
      
      <text>
        <body>
          <div>
            <xsl:apply-templates
              select="//div[@id='Page_content_goes_here']/table"/>
          </div>
        </body>
      </text>
      
    </TEI>
    
  </xsl:template>
  
  <!-- LINKS -->
  
  <xsl:template match="a[@class]">
    
    <xsl:choose>
      
      <xsl:when test="@class = 'glossaire'">
        <term ref="{replace(@href, '\.html', '.xml')}">
          <xsl:apply-templates/>
        </term>
      </xsl:when>
      
      <xsl:when test="@class = 'bibliographie'">
        <bibl source="{replace(@href, '\.html', '.xml')}">
          <xsl:apply-templates/>
        </bibl>
      </xsl:when>
      
      <xsl:when test="@class = 'personnage'">
        <persName ref="{replace(@href, '\.html', '.xml')}">
          <xsl:apply-templates/>
        </persName>
      </xsl:when>
      
      <xsl:when test="@class = 'repertoire'">
        <rs type="repertoire"
          ref="{replace(@href, '\.html', '.xml')}">
          <xsl:apply-templates/>
        </rs>
      </xsl:when>
      
      <xsl:when test="@class = 'note'">
        <note target="{@href}"/>
      </xsl:when>
      
      <xsl:otherwise>
        <ref target="{replace(@href, '\.html', '.xml')}">
          <xsl:apply-templates/>
        </ref>
      </xsl:otherwise>
      
      
    </xsl:choose>
    
  </xsl:template>
  
  <!-- REMARK BOX -->
  
  <xsl:template match="div[@class='boite_remarque']">
    <note type="remarque">
      <xsl:apply-templates/>
    </note>
  </xsl:template>
  
  
  
  <!-- TABLE -->
  
  <xsl:template match="div[@id='Page_content_goes_here']/table">
    <xsl:apply-templates/>
  </xsl:template>
  
  <!-- ROWS -->
  
  <xsl:template match="div[@id='Page_content_goes_here']/table/tr">
    
    <xsl:variable name="noteId"
      select="normalize-space((td[1]/a[not(following-sibling::*[1][self::em])]/@id)[1])"/>
    
    <note>
      
      <xsl:if test="$noteId != ''">
        <xsl:attribute name="xml:id"
          select="replace($noteId, '^([0-9]+)_(.+)$', '$2_$1')"/>
      </xsl:if>
      
      <!-- n attribute from third td -->
      <xsl:if test="normalize-space(td[3]) != ''">
        <xsl:attribute name="n"
          select="normalize-space(td[3])"/>
      </xsl:if>
      
      <xsl:choose>
        
        <xsl:when test="contains(td[1]/@class, 'colonne1')">
          <xsl:attribute name="ana" select="'fiction'"/>
        </xsl:when>
        
        <xsl:when test="contains(td[1]/@class, 'couleur_histoire')">
          <xsl:attribute name="ana" select="'histoire'"/>
        </xsl:when>
        
      </xsl:choose>
      
      
      <xsl:apply-templates/>
      
    </note>
    
  </xsl:template>
   
  
  <xsl:template match="hr"/>
  
  <xsl:template match="br"/>
  
  <!-- CELLS -->
 
  <xsl:template match="div[@id = 'Page_content_goes_here']/table/tr/td">
    <xsl:choose>
      <xsl:when test="position() = 1">
        <label><xsl:apply-templates /></label>
      </xsl:when>
      
      
      <xsl:when test="position() = 3"/>
      
      <xsl:otherwise>
        
        <xsl:for-each-group
          select="node()"
          group-ending-with="br">
          
          <xsl:variable name="block"
            select="current-group()[not(self::br)]"/>
          
          <xsl:variable name="txt"
            select="normalize-space(string-join($block//text(), ''))"/>
          
          <xsl:choose>
            
            <!-- BULLET ITEM -->
            <xsl:when test="matches($txt, '^[•-]')">
              
              <list>
                <item>
                  
                  <xsl:for-each select="$block">
                    
                    <xsl:choose>
                      
                      <!-- remove bullet from first text node -->
                      <xsl:when test="position() = 1 and self::text()">
                        <xsl:value-of
                          select="replace(., '^\s*[•-]\s*', '')"/>
                      </xsl:when>
                      
                      <xsl:otherwise>
                        <xsl:apply-templates select="."/>
                      </xsl:otherwise>
                      
                    </xsl:choose>
                    
                  </xsl:for-each>
                  
                </item>
              </list>
              
            </xsl:when>
            
            <!-- NORMAL PARAGRAPH -->
            <xsl:otherwise>
              
              <xsl:choose>
                
                <!-- already contains XHTML paragraphs -->
                <xsl:when test="$block[self::p]">
                  <xsl:apply-templates select="$block"/>
                </xsl:when>
                
                <!-- create TEI paragraph -->
                <xsl:otherwise>
                  <p>
                    <xsl:apply-templates select="$block"/>
                  </p>
                </xsl:otherwise>
                
              </xsl:choose>
              
            </xsl:otherwise>
            
          </xsl:choose>
          
        </xsl:for-each-group>
        
      </xsl:otherwise>
      
    </xsl:choose>
  </xsl:template>
 
  
  <!-- INLINE -->
  
  <xsl:template match="span[@class='italics'] | em">
    <emph>
      <xsl:apply-templates/>
    </emph>
  </xsl:template>
 
  <xsl:template match="div[@class='borderorange']">
    <note ana="variante">
      <xsl:apply-templates/>
    </note>
  </xsl:template>
  
  <xsl:template match="div[@class='bordergreen']">
    <note ana="poete">
      <xsl:apply-templates/>
    </note>
  </xsl:template>
  
  <xsl:template match="div[@class='interruption']">
    <note ana="interruption">
      <xsl:apply-templates/>
    </note>
  </xsl:template>
  
  <xsl:template match="div[@class='intercalee']">
    <note ana="intercalee">
      <xsl:apply-templates/>
    </note>
  </xsl:template>
  
  <xsl:template match="div[@class='boite_remarque']">
    <note ana="remarque">
      <xsl:apply-templates/>
    </note>
  </xsl:template>
  
  
  
  <!-- IMAGES -->
  
  <xsl:template match="img">
    
    <figure>
      
      <graphic url="{@src}"/>
      
      <xsl:if test="@alt">
        <figDesc>
          <xsl:value-of select="@alt"/>
        </figDesc>
      </xsl:if>
      
    </figure>
    
  </xsl:template>
  
  <xsl:template match="p">
    <p>
      <xsl:apply-templates/>
    </p>
  </xsl:template>
  
  <!-- LISTS -->
  
  <xsl:template match="ul">
    <list>
      <xsl:apply-templates/>
    </list>
  </xsl:template>
  
  <xsl:template match="li">
    <item>
      <xsl:apply-templates/>
    </item>
  </xsl:template>
 
  <xsl:template match="a[@href and not(@class)]">
    
    <ref target="{replace(@href, '\.html', '.xml')}">
      <xsl:apply-templates/>
    </ref>
    
  </xsl:template>
  
  <xsl:template match="text()[contains(., '«')]">
    
    <xsl:analyze-string
      select="."
      regex="«([^»]+)»">
      
      <!-- quoted content -->
      <xsl:matching-substring>
        <quote>
          <xsl:value-of select="regex-group(1)"/>
        </quote>
      </xsl:matching-substring>
      
      <!-- normal text -->
      <xsl:non-matching-substring>
        <xsl:value-of select="."/>
      </xsl:non-matching-substring>
      
    </xsl:analyze-string>
    
  </xsl:template>
  
  
  <!-- IGNORE -->
  
  <xsl:template match="nav"/>
  <xsl:template match="footer"/>
  <xsl:template match="@onclick"/>
  <xsl:template match="script"/>
  
</xsl:stylesheet>